name: MissionTap
main: org.sotap.MissionTap.MissionTap
version: "1.0"
author: sotapmc
api-version: "1.16"
api: []
softdepend:
  - PlaceholderAPI
depend:
  - Ageing

commands:
  missiontap:
    aliases: ["mt"]
    description: The main command of MissionTap.
    permission: missiontap.command
    permission-message: "You do not have the permission to use the command."
    usage: The command is invalid or you don't have the permission to use it.
permissions:
  missiontap.all:
    description: Admin node for the plugin.
    default: op
    children:
      missiontap.daily: true
      missiontap.weekly: true
      missiontap.inprogress: true
      missiontap.special: true
      missiontap.init: true
      missiontap.player: true
      missiontap.reload: true
  missiontap.daily:
    description: Show daily mission menu.
    default: true
  missiontap.weekly:
    description: Show weekly mission menu.
    default: true
  missiontap.inprogress:
    description: Show inprogress menu.
    default: true
  missiontap.special:
    description: Show special mission menu.
    default: true
  missiontap.init:
    description: Initialize required data.
    default: op
  missiontap.player:
    description: Controls player.
    default: op
  missiontap.reload:
    description: Reloads plugin.
    default: op